### get all persons
GET http://localhost:3001/api/persons/

### get find person
GET http://localhost:3001/api/persons/5fe0611215d41228f800e362


### Add user to phonebook
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name":"Mary Poppendieck",
    "number":"110-121-120"
}

### Delete user from phonebook 5fe146de0ef2a54737d8b811
DELETE  http://localhost:3001/api/persons/5

### Update user 
PUT  http://localhost:3001/api/persons/5fe0611215d41228f800e362
Content-Type: application/json

{
    "name":"Anna",
    "number":"121-010-211"
}


